
package parser.csv;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.text.Normalizer;

public class CSVReader {
    
    public static void csvToProlog(File csvFile, File prologFile) throws Exception {
        
        BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(csvFile), "UTF8"));

        FileOutputStream fos = new FileOutputStream(prologFile);
        BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(fos));
        
        String line = br.readLine();
        
        bw.write("% Ouput prolog file generated by the parser. Line format:");
        bw.newLine();
        bw.write("% " + Normalizer.normalize(line, Normalizer.Form.NFD).replaceAll("\\p{InCombiningDiacriticalMarks}+", ""));
        bw.newLine();
        bw.newLine();
        
        while ((line = br.readLine()) != null) {

            Paragem paragem = new Paragem();
            paragem.loadFromString(line);
            
            bw.write(paragem.toPrologFact()); 
            bw.newLine();
        }

        br.close();
        bw.flush();
        bw.close();
    }
}